name: CI

on: [push]

env: 
  BUILD_NAME: ExampleProjectName
  UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}
  UNITY_ACTIVATION_FILE: ./unity3d.alf

jobs:
  test:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.2.11f1
    steps:
    - uses: actions/checkout@v2
    - name: sudo
      run: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
    - name: Before
      run: chmod +x ./ci/before_script.sh && sudo ./ci/before_script.sh
    - name: Edit mode tests
      run: chmod +x ./ci/test.sh && sudo ./ci/test.sh
      env:
        TEST_PLATFORM: editmode
    - name: Play mode tests
      run: chmod +x ./ci/test.sh && ./ci/test.sh
      env:
        TEST_PLATFORM: playmode
