name: CI

on: [push]

env: 
  BUILD_NAME: ExampleProjectName
  UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}
  UNITY_ACTIVATION_FILE: ./unity3d.alf
  UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.2.11f1
    steps:
    - uses: actions/checkout@v2
    - name: Sudo
      run: apt-get update && apt-get install sudo
    - name: Chown
      run: sudo chown -R $USER:$USER $HOME/
    - name: Before
      run: chmod +x ./ci/before_script.sh && ./ci/before_script.sh
    - name: Edit mode tests
      run: chmod +x ./ci/test.sh && ./ci/test.sh
      env:
        TEST_PLATFORM: editmode
    - name: Play mode tests
      run: chmod +x ./ci/test.sh && ./ci/test.sh
      env:
        TEST_PLATFORM: playmode
